### ISSUE TITLE
Change Event Listener to keyup instead of keydown for automatic conversion to emojis.

### ISSUE THREAD

**Issue by wrongsahil** [prabhakar267/whatsapp-emoticons#1]

**Comment by prabhakar267** [comment]
@sahil865gupta I did this intentionally because many times i want to send the **text smiley** instead of **emoticon**
Still we can think of some way around this

**Comment by wrongsahil** [comment]
@prabhakar267 ok but if i try to put emoji in the end of the sentence and then send it, test smiley is send instead of emoji. Its not a big issue i think.
