### ISSUE TITLE
do not convert if the text smiley is not in the end of text

### ISSUE THREAD

**Issue by prabhakar267** [prabhakar267/whatsapp-emoticons#3]
If someone has pasted some text (example- a URL) in WhatsApp web text box, it should not convert all the emoticons inside the text
Only the **smileys** in the end should be converted.

**Comment by Tapemaster21** [comment]
So what is happening when pasting a URL for you something like http:// would be http😕/ or something? 

Would including a space on the faces it's looking for ":)" -> " :)" solve that issue? 

 I don't have whatsapp to test this so I can't really open a pullrequest for hacktoberfest, but I had that thought.

**Comment by collnwalkr** [comment]
I'll take a crack at it. I like @Tapemaster21 idea. A possible solution would be to detect if it a) there is a space before the emoji or b) it is at the beginning of the content editable area.

I'm also thinking it might be a good idea to only enter an emoji if the user presses down the space-bar or submits the message.

**Comment by collnwalkr** [comment]
check #4 for possible fix

**Comment by prabhakar267** [comment]
@Tapemaster21 Yes i think this would solve the problem
@collnwalkr  I will see your PR
